[package]
name = "ffi"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vrisc = { path = ".." }
rav1e = { version = "0.7.1" }
yuvutils-rs = { version = "0.4.13" }

[dev-dependencies]
proptest = "1.5.0"

[build-dependencies]
csbindgen = "1.8.0"
