[package]
name = "ffi"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vrisc = { path = ".." }

[dev-dependencies]
proptest = "1.5.0"

[build-dependencies]
csbindgen = "1.8.0"
